apps/main/urls.py
from django.urls import path
from apps.main import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'


urlpatterns = [
    path('', views.MainPageView.as_view(), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pwa.urls')),
    path('', include('apps.main.urls', namespace='main'), name='index'),
]

apps/main/models/client.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Client(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('Имя'))
    phone = models.CharField(max_length=255, verbose_name=_('Телефон'))
    blocked = models.BooleanField(default=False, verbose_name=_('Заблокирован'))

    def __str__(self):
        return f'{self.name} - {self.phone}'

    class Meta:
        verbose_name = _('Клиент')
        verbose_name_plural = _('Клиенты')

apps/main/models/review.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Review(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('Имя'))
    avatar = models.URLField(verbose_name=_('Ссылка на аватар'))
    text = models.TextField(verbose_name=_('Текст отзыва'))
    score = models.IntegerField(verbose_name=_('Оценка (1-5)'))
    rated = models.CharField(max_length=255, verbose_name=_('Дата публикации отзыва'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Отзыв')
        verbose_name_plural = _('Отзывы')

apps/main/models/window.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from .client import Client

import locale
locale.setlocale(
    category=locale.LC_ALL,
    locale="ru_RU.UTF-8"  # Note: do not use "de_DE" as it doesn't work
)


class Window(models.Model):
    date = models.DateTimeField(verbose_name=_('Окошко'))
    done = models.BooleanField(verbose_name=_('Выполнено'), default=False)
    client = models.ForeignKey(
        Client, on_delete=models.CASCADE, related_name='windows',
        verbose_name=_('Клиент'), null=True, blank=True
    )

    def __str__(self):
        return self.date.strftime('%a %d %B %Y - %H:%M')

    class Meta:
        verbose_name = _('Окошко')
        verbose_name_plural = _('Окошки')

apps/main/models/works.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Works(models.Model):
    url = models.URLField(verbose_name=_("Ссылка на картинку"))

    class Meta:
        verbose_name = _("Мои работы")
        verbose_name_plural = _("Мои работы")

    def __str__(self):
        return self.url

apps/proxy/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
# Create your models here.


class Proxy(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("Название"))
    url = models.TextField(verbose_name=_("URL"))

    def __str__(self):
        return self.name

apps/main/forms.py
from datetime import datetime, timedelta
from string import punctuation, whitespace

from django import forms
from django.forms import ValidationError
from django.utils.translation import gettext_lazy as _
from django.utils.timezone import get_current_timezone

from .models import Window



def format_phone(value):
    characters_to_remove = punctuation.replace('+', '') + whitespace
    value = ''.join(i for i in value if i not in characters_to_remove)
    if value.startswith('8'):
        return '+7' + value[1:]
    return value


def validate_phone_lenght(value):
    if len(value) != 12:
        raise ValidationError('Некорректный номер')


def validate_phone(value):
    if not value[1:].isdigit():
        raise ValidationError('Только цифры')


class PhoneField(forms.CharField):

    def to_python(self, value: str) -> str:
        return format_phone(value)

    def validate(self, value) -> None:
        super().validate(value)
        validate_phone(value)
        validate_phone_lenght(value)


class RegistrationForm(forms.Form):
    name = forms.CharField(required=True)
    phone = PhoneField(required=True)
    window = forms.ModelChoiceField(
        queryset=Window.objects.none(),
        empty_label=_('Выберите окошко'),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['window'].queryset = Window.objects.filter(
            client=None,
            date__gt=datetime.now(get_current_timezone()) + timedelta(hours=19)
        )

apps/main/views.py
import os

from django.shortcuts import render
from django.views.generic import View

from django_htmx.http import retarget

from apps.bot import bot, markup

from .models import Window, Review, Client, Works
from .forms import RegistrationForm
from datetime import datetime, timedelta

from django.utils.timezone import get_current_timezone

class MainPageView(View):

    def get(self, request):
        return render(request, 'main/index.html', {
            'works': Works.objects.all(),
            'reviews': Review.objects.all(),
            'form': RegistrationForm(),
        })

    def post(self, request):

        form = RegistrationForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            phone = form.cleaned_data['phone']
            client, created = Client.objects.get_or_create(
                phone=phone,
                defaults={
                    'name': name,
                    'phone': phone,
                }
            )
            if client.blocked:
                response = render(request, 'main/success.html', {'blocked': True})
                return retarget(response, '#body')

            window = Window.objects.get(id=request.POST['window'])
            window.client = client
            window.save()

            text_to_admin = (
                f'Запись на маникюр:\n'
                f'{name}\n'
                f'{phone}\n'
                f'{window}\n'
            )
            if created:
                text_to_admin += 'Новый клиент'

            send_admins(text_to_admin, markup(window.id))

            response = render(request, 'main/success.html')

            return retarget(response, '#body')

        else:
            return render(request, 'main/includes/index/form.html', {'form': form})


def send_admins(message, markup):
    for admin in os.environ.get("TG_ADMINS").split(","):
        bot.send_message(int(admin), message, reply_markup=markup)

apps/main/templates/main/base.html
{% load static %}
{% load django_htmx %}
{% load livereload_tags %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
    <script defer src="{% static 'js/htmx.min.js' %}"></script>
    <script defer src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    {% livereload_script %}
    {% django_htmx_script %}
    <title>Вита - маникюр</title>
  </head>
  <body data-bs-theme="dark" id="body">
    {% block content %}
    {% endblock content %}
  </body>
</html>

apps/main/templates/main/includes/footer.html
{% load static %}

<footer class="py-4 pt-md-5 border-warning border-top bg-body-tertiary"
        id="footer">
  <div class="row m-auto text-center">
    <div class="col">
      <h2>Мои контакты</h2>
    </div>
  </div>
  <div class="row m-auto text-center">
    <div class="col">
      <h2>+7 (905) 960 26-16</h2>
    </div>
  </div>
  <br />
  <br />
  <div class="row m-auto text-center">
    <div class="col">
      <h2>Я в социальных сетях</h2>
    </div>
  </div>
  <br />
  <div class="row m-auto text-center">
    <div class="col">
      <a class="me-5"
         href="https://api.whatsapp.com/message/J3MYEINZJEUNN1?autoload=1&app_absent=0">
        <img width="40" src="{% static 'icons/whatsapp.svg' %}" alt="vk" />
      </a>
      <a href="https://vk.com/vi_manicure">
        <img width="40" src="{% static 'icons/vk.svg' %}" alt="vk" />
      </a>
    </div>
  </div>
  <br />
</footer>

apps/main/templates/main/includes/header.html
{% load static %}

<nav class="navbar sticky-top navbar-expand-lg bg-body-tertiary">
  <div class="container m-auto my-2">
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'main:index' %}">Вита - Маникюр</a>
    <div class="d-flex order-lg-2">
      <ul class="navbar-nav me-2 mb-lg-0">
        <li class="nav-item">
          <a href="https://api.whatsapp.com/message/J3MYEINZJEUNN1?autoload=1&app_absent=0">
            <img width="28" src="{% static 'icons/whatsapp.svg' %}" alt="whatsapp" />
          </a>
        </li>
      </ul>
      <ul class="navbar-nav mb-lg-0">
        <li class="nav-item" style="color:white;">
          <a href="https://vk.com/vi_manicure">
            <img width="28" src="{% static 'icons/vk.svg' %}" alt="vk" />
          </a>
        </li>
      </ul>
    </div>
    <div class="collapse navbar-collapse order-lg-1"
         id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#about">Обо мне</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#works">Мои работы</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#reviews">Отзывы</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#window">Записаться</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#footer">Контакты</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

apps/main/templates/main/includes/index/about.html
{% load static %}

<div class="bg-image" id="about" style='background-image: url("{% static 'images/bg-2.jpg' %}");background-position: 0% 40%;'>
  <div class="img-overlay d-flex justify-content-center align-items-center">
    <div class="row px-2 w-100">
      <div class="col">
        <h1 class="text-center top-0">Обо мне</h1>
        <p>✅ Долгая носка без сколов и отслоек</p>
        <p>✅ Маникюр за 2 часа</p>
        <p>✅ Более 150 цветов и дизайнов на любой вкус и цвет</p>
        <p>✅ Одноразовые расходники и 3-х этапная стерилизация инструментов (крафт-пакет вскрывается при Вас)</p>
        <p>✅ Удобная транспортная развязка</p>
        <br />
        <p class="d-none d-lg-block">Xoчешь маникюр, котоpый дepжится БEЗ CKОЛОВ И ОTСЛОЕK 4-5 нeдeль?</p>
        <p class="d-none d-lg-block">Думаешь такоe нeвoзмoжнo?</p>
        <p class="d-none d-lg-block">
          Cкоpee пиши или звони мнe и eдинственноe o чём ты будешь думaть - кaкой цвет выбpать в cледующий раз. 🤪
        </p>
      </div>
    </div>
  </div>
</div>

apps/main/templates/main/includes/index/form.html
{% load widget_tweaks %}
{% load static %}

<div class="bg-image" id="window" style='background-image: url("{% static 'images/bg-4.jpg' %}");background-position: 0% 30%;'>
  <div class="img-overlay d-flex justify-content-center align-items-center">
    <div class="row px-2 w-30">
      <div class="col">
        <form method="post" action="{% url 'main:index' %}">
          {% csrf_token %}
          <legend>Записаться на маникюр</legend>
          <div class="mb-3">
            {% render_field form.name type='text' class='form-control' id='id_name' name='name' placeholder='Ваше имя' %}
            {{ form.name.errors }}
          </div>
          <div class="mb-3">
            {% render_field form.phone type='tel' class='form-control' id='id_phone' name='phone' placeholder='Номер телефона' %}
            {{ form.phone.errors }}
          </div>
          <div class="mb-3">
            {% render_field form.window type='select' class='form-select' id='id_window' name='window' %}
            {{ form.window.errors }}
          </div>
          <div class="row">
            <div class="col text-center">
              <button type="submit"
                      class="btn btn-warning"
                      hx-post="{% url 'main:index' %}"
                      hx-target="#window">Записаться</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

apps/main/templates/main/includes/index/main.html
{% load static %}

<div class="bg-image" id="main" style='background-image: url("{% static 'images/bg-1.jpg' %}");background-position: 0% 30%;'>
  <div class="img-overlay d-flex justify-content-center align-items-center">
    <div class="row w-100">
      <div class="col text-center">
        <h1>Запись к мастеру маникюра</h1>
        <br />
        <h2>Маникюр с покрытием, наращивание ногтей💅 г. Кемерово, Р-н Южный, ул. Космическая, 27🏠</h2>
        <br />
        <a class="btn btn-warning" href="#window">Записаться</a>
      </div>
    </div>
  </div>
</div>

apps/main/templates/main/includes/index/reviews.html
{% load static %}
{% load custom_tags %}

<div class="bg-image" id="reviews" style='background-image: url("{% static 'images/bg-3.jpg' %}");background-position: 0% 30%;'>
  <div class="img-overlay d-flex justify-content-center align-items-center">
    <div class="row w-100" style="margin: auto">
      <div class="col">
        <div id="carouselExampleCaptions" class="carousel slide p-2">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <div class="card-group">
                <div class="card border-0 bg-transparent p-2">
                  <div class="col-md-3 mx-auto">
                    <img src="{{ reviews.0.avatar }}"
                         class="d-block w-50 card-img-top mx-auto rounded-circle"
                         alt="..." />
                  </div>
                  <div class="card-body">
                    <div class="card-title text-center">
                      <h5>{{ reviews.0.name }}</h5>
                      {% for star in reviews.0.score|range_ %}
                        <img src="{% static 'icons/star-fill.svg' %}" alt="" />
                      {% endfor %}
                    </div>
                    <p class="d-none d-sm-block card-text text-center">{{ reviews.0.text }}</p>
                    <p class="d-bloc d-sm-none card-text text-center text-truncate">{{ reviews.0.text }}</p>
                    <p class="card-text text-center">
                      <small class="text-muted">{{ reviews.0.rated }}</small>
                    </p>
                  </div>
                </div>
              </div>
            </div>
            {% for review in reviews|slice:'1:' %}
              <div class="carousel-item">
                <div class="card-group">
                  <div class="card border-0 bg-transparent">
                    <div class="col-md-3 mx-auto">
                      <img src="{{ review.avatar }}"
                           class="d-block w-50 card-img-top mx-auto rounded-circle"
                           alt="..." />
                    </div>
                    <div class="card-body">
                      <div class="card-title text-center">
                        <h5>{{ review.name }}</h5>
                        {% for star in review.score|range_ %}
                          <img src="{% static 'icons/star-fill.svg' %}" alt="" />
                        {% endfor %}
                      </div>
                      <p class="d-none d-sm-block card-text text-center">{{ review.text }}</p>
                      <p class="d-bloc d-sm-none card-text text-center text-truncate">{{ review.text }}</p>
                      <p class="card-text text-center">
                        <small class="text-muted">{{ review.rated }}</small>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
          <button class="carousel-control-prev"
                  type="button"
                  data-bs-target="#carouselExampleCaptions"
                  data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next"
                  type="button"
                  data-bs-target="#carouselExampleCaptions"
                  data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

apps/main/templates/main/includes/index/works.html
{% load static %}

<div id="carouselExample" class="carousel slide">
  <div class="carousel-inner" id="works">
    <div class="carousel-item active">
      <div class="col col-md-6 mx-auto">
        <img src="{{ works.0.url }}" class="d-block w-100" alt="..." />
      </div>
      <div class="carousel-caption">
        <a href="#window" class="btn btn-warning">Записаться</a>
      </div>
    </div>
    {% for work in works|slice:"1:" %}
      <div class="carousel-item">
        <div class="col col-md-6 mx-auto">
          <img src="{{ work.url }}" class="d-block w-100" alt="..." />
        </div>
        <div class="carousel-caption">
          <a href="#window" class="btn btn-warning">Записаться</a>
        </div>
      </div>
    {% endfor %}
  </div>
  <button class="carousel-control-prev"
          type="button"
          data-bs-target="#carouselExample"
          data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next"
          type="button"
          data-bs-target="#carouselExample"
          data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

apps/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
  {% include 'main/includes/header.html' %}

  {% include 'main/includes/index/main.html' %}
  {% include 'main/includes/index/about.html' %}
  {% include 'main/includes/index/works.html' %}
  {% include 'main/includes/index/reviews.html' %}
  {% include 'main/includes/index/form.html' %}

  {% include 'main/includes/footer.html' %}
{% endblock content %}

apps/main/templates/main/success.html
{% extends 'main/base.html' %}

{% block content %}
  <div class="bg-image-1" style="min-height: 100vh;">
    <div class="img-overlay d-flex justify-content-center align-items-center">
      <div class="row">
        <div class="col text-center">
          {% if blocked %}
            <h1>Ой, что-то пошло не так.</h1>
          {% else %}
            <h1>Ваша заявка принята!</h1>
            <h2>Я свяжусь с вами в ближайшее время</h2>
          {% endif %}
          <a href="{% url 'main:index' %}" class="btn btn-warning">Вернуться на главную</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}